name: Build

on:
    push:
    schedule:
        - cron: '0 4 * * TUE'

jobs:

  build:
    name: "Build (& Publish)"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
            push: true
            tags: ${{ secrets.DOCKER_HUB_IMAGE }}
